version: '3'
services:

  postgres:
    container_name: dev-undok-postgres
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dev123
      - POSTGRES_USER=undok